### ISSUE TITLE
Include assets

### ISSUE THREAD

**Issue by ghost** [Stratus211/prj-rev-bwfs-dasmoto#3]
https://github.com/Stratus211/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/Home.html#L13

Include your website's assets (in this case images) in your project and provide a relative file path to them in your `img` tags. 

It's always better to provide static assets up front instead of depending on external URLs that could fail or otherwise become unavailable.

**Comment by Stratus211** [comment]
okay, I didn't know if it would link after submitting it to github. This being my first time I have used it. In the future will do!
